# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gnarails-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - gnarails-

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: install dependencies
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          paths:
            - vendor/bundle
          key: gnarails-{{ checksum "Gemfile.lock" }}

      # Tests
      - run:
          name: RSpec
          command: bundle exec rspec

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

  build-rails:
    docker:
      - image: ruby:2.4.2

    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
          - gnarails-build-rails-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - gnarails-build-rails-

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: apt-get -y -qq update && apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: Install Dependencies
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          paths:
            - vendor/bundle
          key: gnarails-build-rails-{{ checksum "Gemfile.lock" }}

      # Generate test app
      - run:
          name: Generate Test App
          command: sh ./bin/generate-test-app.sh && mkdir rails-app && cp -r ~/project/rails-test-app ~/project/rails-app/

      # Save to shared workspace
      - persist_to_workspace:
          root: rails-app
          paths:
            - rails-test-app

  test-rails-app:
    docker:
      - image: circleci/ruby:2.4.2-stretch-node-browsers
        environment:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: ubuntu
          DATABASE_URL: "postgres://ubuntu@localhost:5432/rails-test-app-test"
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: rails-test-app-test

    steps:
      - attach_workspace:
          at: /tmp/rails-test-app

      # Pull rails app from shared workspace
      - run:
          name: Copy Test App
          command: cp -r /tmp/rails-test-app/rails-test-app/* ~/project

      # Restore bundle cache
      - restore_cache:
          keys:
          - gnarails-test-rails-app-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - gnarails-test-rails-app-

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: install dependencies
          command: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          paths:
            - vendor/bundle
          key: gnarails-test-rails-app-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Create database
          command: bundle exec rake db:create && bundle exec rake db:migrate

      # Tests
      - run:
          name: RSpec
          command: bundle exec rspec

     # Security analysis
      - run:
          name: Bundler Audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: Brakeman
          command: ./script/brakeman

      # Pronto
      - run:
          name: Pronto
          command: ./script/ci_pronto

      # Save Brakeman
      - store_artifacts:
          path: tmp/brakeman.html
          destination: security/brakeman.html

      # Save Coverage Analysis
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_test
      - build-rails
      - test-rails-app:
          requires:
            - build-rails
