version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.5
jobs:
  unit_test:
    docker:
      - image: cimg/ruby:2.7.4-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: install ruby dependencies
          command: bundle install

      # Yarn install dependencies
      - run:
          name: install js dependencies
          command: yarn install

      # Tests
      - run:
          name: RSpec
          command: ./bin/rspec

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

  build-rails:
    docker:
      - image: cimg/ruby:2.7.4-browsers

    steps:
      - checkout

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Install rake after installing specific version of bundler
      - run:
          name: Install rake
          command: gem install rake

      # Bundle install dependencies
      - run:
          name: Install ruby Dependencies
          command: bundle install

      # Yarn install dependencies
      - run:
          name: install js dependencies
          command: yarn install

      # Generate test app
      - run:
          name: Generate Test App
          command: sh ./bin/generate-test-app.sh

      # Move test app
      - run:
          name: Move Test App
          command: mkdir rails-app && cp -r ~/project/rails-test-app ~/project/rails-app/

      # Save to shared workspace
      - persist_to_workspace:
          root: rails-app
          paths:
            - rails-test-app

  test-rails-app:
    docker:
      - image: cimg/ruby:2.7.4-browsers
        environment:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: ubuntu
          DATABASE_URL: "postgres://ubuntu@localhost:5432/rails-test-app-test"
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: rails-test-app-test

    steps:
      - browser-tools/install-browser-tools
      - attach_workspace:
          at: /tmp/rails-test-app

      # Pull rails app from shared workspace
      - run:
          name: Copy Test App
          command: cp -r /tmp/rails-test-app/rails-test-app/* ~/project

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: Install ruby dependencies
          command: bundle install

      # Yarn install dependencies
      - run:
          name: install js dependencies
          command: yarn install

      # Database setup
      - run:
          name: Create database
          command: bin/rails db:setup

      # Generate Assets
      - run:
          name: Generate Assets
          command: ./bin/rails assets:precompile

      # Tests
      - run:
          name: RSpec
          command: ./bin/rspec

     # Security analysis
      - run:
          name: Bundler Audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: Brakeman
          command: ./bin/brakeman

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

      # Save Brakeman
      - store_artifacts:
          path: tmp/brakeman.html
          destination: security/brakeman.html

      # Save Coverage Analysis
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_test
      - build-rails
      - test-rails-app:
          requires:
            - build-rails
