# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: install dependencies
          command: bundle install

      # Tests
      - run:
          name: RSpec
          command: bundle exec rspec

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

  build-rails:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers

    steps:
      - checkout

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Install rake after installing specific version of bundler
      - run:
          name: Install rake
          command: gem install rake

      # Bundle install dependencies
      - run:
          name: Install Dependencies
          command: bundle install

      # Generate test app
      - run:
          name: Generate Test App
          command: sh ./bin/generate-test-app.sh

      # Move test app
      - run:
          name: Move Test App
          command: mkdir rails-app && cp -r ~/project/rails-test-app ~/project/rails-app/

      # Save to shared workspace
      - persist_to_workspace:
          root: rails-app
          paths:
            - rails-test-app

  test-rails-app:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node-browsers
        environment:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: ubuntu
          DATABASE_URL: "postgres://ubuntu@localhost:5432/rails-test-app-test"
      - image: circleci/postgres:13.0
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: rails-test-app-test

    steps:
      - attach_workspace:
          at: /tmp/rails-test-app

      # Pull rails app from shared workspace
      - run:
          name: Copy Test App
          command: cp -r /tmp/rails-test-app/rails-test-app/* ~/project

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle install

      # Database setup
      - run:
          name: Create database
          command: bundle exec rake db:create && bundle exec rake db:migrate

      # Tests
      - run:
          name: RSpec
          command: bundle exec rspec

     # Security analysis
      - run:
          name: Bundler Audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: Brakeman
          command: ./bin/brakeman

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

      # Save Brakeman
      - store_artifacts:
          path: tmp/brakeman.html
          destination: security/brakeman.html

      # Save Coverage Analysis
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_test
      - build-rails
      - test-rails-app:
          requires:
            - build-rails
