version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.5
jobs:
  build:
    docker:
      - image: cimg/ruby:__ruby_version__-browsers
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - browser-tools/install-browser-tools
      - checkout

      # cmake is required by Rugged, a dependency of Pronto
      - run:
          name: Install cmake
          command: sudo apt-get -y -qq update && sudo apt-get -y -qq install cmake

      # Yarn install dependencies
      - run:
          name: install js dependencies
          command: yarn install

      # Bundle install dependencies
      - run:
          name: install ruby dependencies
          command: bundle install

      # Database setup
      - run:
          name: Create database
          command: ./bin/setup

      # Tests
      - run:
          name: RSpec
          command: ./bin/rspec

      # Security analysis
      - run:
          name: Bundler Audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - run:
          name: Brakeman
          command: ./bin/brakeman

      # Pronto
      - run:
          name: Pronto
          command: ./bin/ci_pronto

      # Save Brakeman
      - store_artifacts:
          path: tmp/brakeman.html
          destination: security/brakeman.html

      # Save Coverage Analysis
      - store_artifacts:
          path: coverage
          destination: coverage

      # Save Capybara Screenshots
      - store_artifacts:
          path: tmp/screenshots
          destination: capybara/screenshots
