#!/bin/bash
#
# Script for running pronto on CI
export PRONTO_PULL_REQUEST_ID=${CI_PULL_REQUEST##*/}
echo $PRONTO_PULL_REQUEST_ID

bundle exec pronto run -f text github_pr github_status -c origin/master
