AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'Gemfile'

Metrics/LineLength:
  Max: 100
  Severity: refactor

Style/FrozenStringLiteralComment:
    Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/ParenthesesAroundCondition:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
