name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - run: gem install gnar-style

      - uses: HeRoMo/pronto-action@v1.31.0
