name: Pronto

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: git fetch origin main --depth=1
      - uses: adwerx/pronto-ruby@v2.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.pull_request.base.ref }}
