name: Pronto

on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          fetch-depth: 0
      - uses: adwerx/pronto-ruby@v2.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
