name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin main --depth=1
      - uses: adwerx/pronto-ruby@v2.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
