name: Test Rails App
on: [push]

jobs:
  test-rails-app:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo "HEY"
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - run: echo "HEY"
      # - name: Setup cmake
      #   uses: jwlawson/actions-setup-cmake@v1.12
      #   with:
      #     github-api-token: ${{ secrets.GITHUB_TOKEN }}
      #     cmake-version: '3.16.x'

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - name: Generate Binstubs
        run: bundle binstubs bundler

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # - name: Setup test database
      #   env:
      #     RAILS_ENV: test
      #     PGHOST: localhost
      #     PGUSER: myapp
      #   run: |
      #     bin/setup

      - name: Generate Test App
        run: /bin/generate-test-app.sh

      - name: LS
        run: ls

      # - uses: actions/upload-artifact@master
      #   with:
      #     name: rails-test-app
      #     path: path/to/artifact

#     services:
#       postgres:
#         image: postgres:11
#         env:
#           POSTGRES_USER: myapp
#           POSTGRES_DB: myapp_test
#           POSTGRES_PASSWORD: ""
#         ports: ["5432:5432"]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Ruby and install gems
#         uses: ruby/setup-ruby@v1
#         with:
#           bundler-cache: true

#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: 10.13.0
#       - name: Find yarn cache location
#         id: yarn-cache
#         run: echo "::set-output name=dir::$(yarn cache dir)"
#       - name: JS package cache
#         uses: actions/cache@v1
#         with:
#           path: ${{ steps.yarn-cache.outputs.dir }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-
#       - name: Install packages
#         run: |
#           yarn install --pure-lockfile

#       - name: Setup test database
#         env:
#           RAILS_ENV: test
#           PGHOST: localhost
#           PGUSER: myapp
#         run: |
#           bin/rails db:setup

#       - name: Run tests
#         run: bin/rspec
