name: Test Rails App
on: [push, workflow_call]

jobs:
  test-rails-app:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_PASSWORD: password
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: rails-test-app

      - name: LS
        working-directory: '.'
        run: |
          ls

      - name: Install packages
        working-directory: './rails-test-app'
        run: |
          yarn install --pure-lockfile

      - name: Generate Assets
        working-directory: './rails-test-app'
        run: bin/rails assets:precompile

      - name: Setup DB
        working-directory: './rails-test-app'
        run: bin/setup

      - name: Run tests
        working-directory: './rails-test-app'
        run: bundle exec rspec

      - name: Bundler Audit
        working-directory: './rails-test-app'
        run: ./bin/bundle bundle-audit update && bundle exec bundle-audit check

      - name: Brakeman
        working-directory: './rails-test-app'
        run: ./bin/brakeman
